BedrockStreaming/GuzzleHttpBundle

README.md
src/DependencyInjection/Configuration.php
tests/Fixtures/default-config.yml
tests/Units/DependencyInjection/M6WebGuzzleHttpExtension.php

With this fix we can have a simpler client's configuration

Allow to not set base_uri in clients configuration

---

src/DependencyInjection/M6WebGuzzleHttpExtension.php
src/EventDispatcher/GuzzleHttpEvent.php
src/Middleware/EventDispatcherMiddleware.php

For monitoring purpose, we need to know from which client event is thrown.

Add client name in request event

---

src/Handler/CacheTrait.php
tests/Units/Handler/CurlMultiHandler.php

Sometimes we get this error :
```
Catchable Fatal Error: Argument 2 passed to GuzzleHttp\Psr7\Response::__construct()
must be of the type array, null given, called in 
[...]vendor/m6web/guzzle-http-bundle/src/Handler/CacheTrait.php on line 140 and defined
```
There might be an issue when data are unserialized from cache.   That's why I add a check on unserialized data.

Avoid unserialize issues

---

.travis.yml
src/EventDispatcher/GuzzleHttpEvent.php
src/Middleware/EventDispatcherMiddleware.php
tests/Units/Middleware/EventDispatcherMiddleware.php

After a request timeout, the event was not dispatched (no handler to catch the case) and the event stay in memory until the end of the process.
Added :
- Handler to catch request error
- New event 'error' 
- Tests
Disable xdebug for core dump with PHP 7.0 (?)

Fix event dispatcher memory leak

---

src/Middleware/EventDispatcherMiddleware.php
tests/Units/Middleware/EventDispatcherMiddleware.php

Small fix after the last PR : reason is always an exception.

Fix dispatcher event callback for exceptions

---

composer.json
src/DependencyInjection/Configuration.php

Symfony 3 compatibilities :
- `cannotBeEmpty()` is removed

Symfony 3 compatibilities

---

tests/Units/DependencyInjection/M6WebGuzzleHttpExtension.php

It's `protected` and only used in a single unit test file... so no BC break here :+1:

Fix typo in protected getContainerForConfiguration tests method name

---

src/Handler/CacheTrait.php
tests/Units/Handler/CurlMultiHandler.php

cache-control: max-age=0 mean no cache, but on many cache service it means infinite cache

dont cache with a zero ttl

---

src/Handler/CacheTrait.php
tests/Units/Handler/CurlMultiHandler.php

X-headers must be ignored for generate the cache keys.

"X-" headers must be ignored for the cache keys

---

src/DependencyInjection/M6WebGuzzleHttpExtension.php

The extension doesn't configure the curl multi handler correctly. For instance, when `cache_server_errors` is set to `false` and the multi handler is used, its value is set to the default one (`true`).
I added the missing parameters to the curl multi handler setCache method, I took example on the curl handler above.

Fix curl multi handler configuration

---

src/DataCollector/GuzzleHttpDataCollector.php

Add the reset function and move the constructor code into.

Fix Symfony 3.4 DataColector deprecation

---

src/Resources/config/datacollector.yml
src/Resources/views/Collector/guzzlehttp.html.twig

Since 2.8, Symfony recommends to use the new notation to reference Twig templates : @BundleName/directory/filename.html.twig
So we need to fix `M6WebGuzzleHttpBundle:Collector:guzzlehttp` to
`@M6WebGuzzleHttp/Collector/guzzlehttp.html.twig`
https://symfony.com/doc/current/templating.html#referencing-templates-in-a-bundle

[SF4] Use new reference notation for twig templates

---

composer.json
src/Handler/CacheTrait.php
src/Handler/CurlHandler.php
src/Handler/CurlMultiHandler.php
src/Middleware/EventDispatcherMiddleware.php
tests/Units/Middleware/EventDispatcherMiddleware.php

Using the bundle with event-dispatcher 4.3 was throwing an exception because the first param of `dispatch()` is expected to be an event and not a string.
- Update params order
- Use `LegacyEventDispatcherProxy` to decorate `eventDispatcher` and still be compatible with previous versions.

fix: decorate event dispatcher and invert dipatch() params

---

src/Middleware/EventDispatcherMiddleware.php

if `LegacyEventDispatcherProxy` in the dispatch method try to invoke the `Symfony\Component\EventDispatcher\Debug\WrappedListener` which wait for `Symfony\Component\EventDispatcher\Event` but it receive a`Symfony\Contracts\EventDispatcher\Event` (from AbstractGuzzleHttpEvent)
We need this Legacy event 'decoration'

fix(event-dispatcher): To use the LegacyEventDispatcherProxy we need also to use LegacyEventProxy

---

.travis.yml
README.md
composer.json
src/DataCollector/GuzzleHttpDataCollector.php
src/DependencyInjection/Configuration.php
src/Handler/CurlFactory.php
src/Handler/CurlHandler.php
src/Handler/CurlMultiHandler.php
src/M6WebGuzzleHttpBundle.php
src/Middleware/EventDispatcherMiddleware.php
tests/Units/DependencyInjection/M6WebGuzzleHttpExtension.php
tests/Units/Middleware/EventDispatcherMiddleware.php

- we say in composer.json that we support `>php7.0` but our bundle contains code only compatible with `>php7.1` (nullable typing)... so we already dropped support for php7.0 💃 
- our CI is failing for a while now... because it has been deactivated somehow 🤷‍♂ 
- we depend on `LegacyEventProxy` which is a Symfony `@internal` class... and has been brutally removed in Symfony 5
- supports php7.1 to php7.3 in our CI (php7.4 may work fine but atoum is not compatible with it yet... so we can't test it well)
- enable support for Symfony 5 ~(we didn't test it in a real symfony5 project yet... but at least our tests passes 🤷‍♂)~ (see REAL TESTING section)
- drop support for the old `EventDispatcherInterface::dispatch` param orders
- drop support for unsupported symfony version …

feat(symfony5): support Symfony5 and restore travis ci

---

.coke
.github/PULL_REQUEST_TEMPLATE.md
.php_cs.dist
.travis.yml
Makefile
README.md
composer.json
src/Cache/CacheInterface.php
src/Cache/InMemory.php
src/DataCollector/GuzzleHttpDataCollector.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/M6WebGuzzleHttpExtension.php
src/DependencyInjection/MiddlewarePass.php
src/EventDispatcher/AbstractGuzzleCacheEvent.php
src/EventDispatcher/AbstractGuzzleHttpEvent.php
src/Handler/CacheTrait.php
src/Handler/CurlFactory.php
src/Handler/CurlHandler.php
src/Handler/CurlMultiHandler.php
src/M6WebGuzzleHttpBundle.php
src/Middleware/EventDispatcherMiddleware.php
src/Middleware/MiddlewareInterface.php
tests/Units/Cache/InMemory.php
tests/Units/DependencyInjection/M6WebGuzzleHttpExtension.php
tests/Units/Handler/CurlMultiHandler.php
tests/Units/Handler/FakeCurlMultiHandler.php

- Coke is quite old and best practices have changed
- A makefile is always useful

chore: remove coke, use cs-fixer and add a makefile

---

.gitignore
src/Handler/CacheTrait.php
src/Middleware/EventDispatcherMiddleware.php

If we enable the cache feature. And when the cache does not exist. The answer is empty because it is a stream that is already read during caching.
Rewind the response for get information of stream.

fix(cache): rewind the response stream

---

.github/CODEOWNERS
src/DependencyInjection/Configuration.php
src/M6WebGuzzleHttpBundle.php

I have some deprecations notice from phpunit when using this bundle on a PHP 8 project.
This PR aim fix them.
```
1x: Method "Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension()" might add "?ExtensionInterface" as a native return type declaration in the future. Do the same in child class "M6Web\Bundle\GuzzleHttpBundle\M6WebGuzzleHttpBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
1x: Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "M6Web\Bundle\GuzzleHttpBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.
```
- …

Fix future deprecated

---

src/DataCollector/GuzzleHttpDataCollector.php
src/DependencyInjection/GuzzleHttpPass.php
src/DependencyInjection/M6WebGuzzleHttpExtension.php
src/M6WebGuzzleHttpBundle.php
src/Resources/views/Collector/guzzlehttp.html.twig

We want to have more details in the sf profiler for guzzle requests.
Copied from Symfony HTTP Client profiler
---------------------
**Before**
**After**

Better look&feel profiler

---

Makefile
README.md
src/DependencyInjection/Configuration.php
tests/Fixtures/cache-config-no-server-errors.yml
tests/Fixtures/cache-config.yml

- we thought that sharing the same Guzzle handler between all Guzzle clients would only act on asynchronous requests... but it has also the impact of sharing the same Guzzle middlewares between all Guzzle clients...
- stop to share the same handler for all clients, by default

fix(same_handler): stop to share Guzzle handler by default

---

.github/workflows/ci.yml
README.md
composer.json
src/DependencyInjection/M6WebGuzzleHttpExtension.php
tests/Units/DependencyInjection/M6WebGuzzleHttpExtension.php
tests/Units/Handler/CurlMultiHandler.php
tests/Units/Middleware/EventDispatcherMiddleware.php

[Someone from Guzzle said](https://github.com/guzzle/guzzle/pull/3060#issuecomment-1229480907) that it was the correct way to make asynchronous requests through several clients... and therefore, there is no need to be able to share the handler stack anymore
- when `clients_share_the_same_handler` is `true`, share only the curl handler instead of the entire handler stack
`v5.0.2`

fix(handler_sharing): only share the curl handler instead of the entire handler stack

---

src/DataCollector/GuzzleHttpDataCollector.php

Because default client is name without |`_key`

fix(dataCollector): fix default index

---

composer.json
src/Cache/InMemory.php
src/DependencyInjection/M6WebGuzzleHttpExtension.php
src/Handler/CacheTrait.php
src/Handler/CurlFactory.php
src/M6WebGuzzleHttpBundle.php
src/Middleware/EventDispatcherMiddleware.php

CI is failing on master due to coding style changes & new major version on `guzzlehttp/promises`
* Fixed `friendsofphp/php-cs-fixer` version to avoid random changes, and applied it
* Require `guzzlehttp/promises` in tests up to version 1

fix: fixed php-cs-fixer version and applied coding style

---

src/Handler/CurlFactory.php

The curlInfo dynamic property is deprecated in PHP8.2 and will be removed in favor of [the native `on_stat` option](https://docs.guzzlephp.org/en/latest/request-options.html#on-stats)
`@deprecated` should trigger warnings in CI to notice people about this change

chore: mark class as deprecated before next major version

---

.github/workflows/ci.yml
README.md
composer.json
src/Cache/CacheInterface.php
src/Cache/InMemory.php
src/DataCollector/GuzzleHttpDataCollector.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/GuzzleHttpPass.php
src/DependencyInjection/M6WebGuzzleHttpExtension.php
src/DependencyInjection/MiddlewarePass.php
src/EventDispatcher/AbstractGuzzleCacheEvent.php
src/EventDispatcher/AbstractGuzzleHttpEvent.php
src/Handler/CacheTrait.php
src/Handler/CurlFactory.php
src/Handler/CurlHandler.php
src/Handler/CurlMultiHandler.php
src/M6WebGuzzleHttpBundle.php
src/Middleware/EventDispatcherMiddleware.php
src/Middleware/HostForwarderMiddleware.php
src/Middleware/MiddlewareInterface.php
tests/Units/Cache/InMemory.php
tests/Units/DependencyInjection/M6WebGuzzleHttpExtension.php
tests/Units/Handler/CurlMultiHandler.php
tests/Units/Handler/FakeCurlMultiHandler.php
tests/Units/Middleware/EventDispatcherMiddleware.php
tests/Units/Middleware/HostForwarderMiddleware.php

much cleanup, such nice
* dropped unsupported Symfony versions
* dropped unsupported PHP versions
* dropped Guzzle 6 as [it doesn't support PHP8](https://github.com/guzzle/guzzle#version-guidance)
* applied latest CS rules
Should be included in next major version

feat!: update all dependencies to latest supported versions

---

.github/workflows/ci.yml
composer.json
phpstan.neon
rector.php
src/DataCollector/GuzzleHttpDataCollector.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/GuzzleHttpPass.php
src/DependencyInjection/M6WebGuzzleHttpExtension.php
src/EventDispatcher/AbstractGuzzleCacheEvent.php
src/EventDispatcher/AbstractGuzzleHttpEvent.php
src/Handler/CacheTrait.php
src/Middleware/EventDispatcherMiddleware.php
src/Middleware/HostForwarderMiddleware.php

`$quality += 2`
Setup PHPStan & Rector without caring about fixing everything : that will come later

feat: setup phpstan & rector
